### ISSUE TITLE
Migrating from Angular 9.1 to 10

### ISSUE THREAD

**Issue by dspizzirri-ge** [MichaelKravchuk/angular-resize-element#10]
Hi, I was trying to update my project but these two errors appeared.

Any idea?

I am using angular-resize-element 1.1.8

Package "angular-resize-element" has an incompatible peer dependency to "@angular/common" (requires "^8.2.6" (extended), would install "10.2.5").

Package "angular-resize-element" has an incompatible peer dependency to "@angular/core" (requires "^8.2.6" (extended), would install "10.2.5"). 

What can I do to solve it?

**Comment by MichaelKravchuk** [comment]
Hi @dspizzirri-ge! You can try new version 1.2.0 of the package.

**Comment by dspizzirri-ge** [comment]
That worked, thank you!
