### ISSUE TITLE
style.css isn't created

### ISSUE THREAD

**Issue by aiganymus** [MichaelKravchuk/angular-resize-element#3]
There is no styles.css file in "node_modules/angular-resize-element/bundles" folder.
![Screenshot_1](https://user-images.githubusercontent.com/24257171/59334346-173d3a00-8d1c-11e9-8535-4370ccd8654d.png)

**Comment by a-r-db** [comment]
Same issue here.

**Comment by Sireini** [comment]
Same issue here, you guys found an other solution?

**Comment by a-r-db** [comment]
Instead of using an arbitrary library I went with the old school css attribute.
>    resize: both;

I figure it would be safer than using these loosely maintained libraries.
You could try to use mixed tools. I hear react.js is really good.

**Comment by MichaelKravchuk** [comment]
I fixed it. Now you can use scss file.
