### ISSUE TITLE
Not compatible with Angular 9+

### ISSUE THREAD

**Issue by ypkkhatri** [MichaelKravchuk/angular-resize-element#6]
ERROR in node_modules/angular-resize-element/lib/angular-resize-element.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    

> This likely means that the library (angular-resize-element) which declares AngularResizeElementModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

```typescript
    1| export declare class AngularResizeElementModule {
```

**Comment by ypkkhatri** [comment]
Issue resolved by rebuilding the project.

**Comment by kurtiev** [comment]
@MichaelKravchuk this really make this repo useless without support Angular 9+

**Comment by dspizzirri-ge** [comment]
Any news about compatibility with Angular 9+?

**Comment by MichaelKravchuk** [comment]
duplicate https://github.com/MichaelKravchuk/angular-resize-element/issues/10#issuecomment-851364038

**Comment by ypkkhatri** [comment]
@MichaelKravchuk This one created first, so #10 is duplicate.
