### ISSUE TITLE
 Cannot assign to 'targetElement' because it is a read-only property.

### ISSUE THREAD

**Issue by ricardo-hl** [MichaelKravchuk/angular-resize-element#7]
This is easy:

![image](https://user-images.githubusercontent.com/4327356/104330724-e010ab00-54b3-11eb-8985-2fe354a77ade.png)

export declare class AngularResizeElementDirective {
    private readonly elementRef;
    private readonly renderer2;
    private mouseUpListener;
    private mouseMoveListener;
    private targetElementWidthValue;
    private targetElementHeightValue;
    private targetElementTopValue;
    private targetElementLeftValue;
    private originalEvent;
    targetElement: HTMLElement | ElementRef;
    direction: AngularResizeElementDirection;
    proportionalResize: boolean;
    rect: Position;
    readonly applyClass = "resizing";
    resizeStart: EventEmitter<AngularResizeElementEvent>;
    resize: EventEmitter<AngularResizeElementEvent>;
    resizeEnd: EventEmitter<AngularResizeElementEvent>;
    constructor(elementRef: ElementRef, renderer2: Renderer2);
    onMouseDown(evt: MouseEvent): void;
    private onMouseUp;
    private onMouseMove;
    private setOriginalData;
    private readonly targetNativeElement;
    private generateValuesForEvent;
    static ɵfac: ɵngcc0.ɵɵFactoryDef<AngularResizeElementDirective, never>;
    static ɵdir: ɵngcc0.ɵɵDirectiveDefWithMeta<AngularResizeElementDirective, "[resize], [resizeStart], [resizeEnd]", never, { "applyClass": "applyClass"; "targetElement": "targetElement"; "direction": "direction"; "proportionalResize": "proportionalResize"; "rect": "rect"; }, { "resizeStart": "resizeStart"; "resize": "resize"; "resizeEnd": "resizeEnd"; }, never>;
}

**Comment by MichaelKravchuk** [comment]
fixed
